Repository taku-project/taku-backend, pull requests merged in 2024-12, with the labels that each got.

#9 pull_request_template 생성
  .github/pull_request_template
Labels: 📃 Docs

#10 [ADMIN] 관리자 페이지 기본 화면 추가
  src/main/java/com/ani/taku_backend/admin/controller/AdminController.java
  src/main/resources/static/assets/demo/chart-area-demo.js
  src/main/resources/static/assets/demo/chart-bar-demo.js
  src/main/resources/static/assets/demo/chart-pie-demo.js
  src/main/resources/static/assets/demo/datatables-demo.js
  src/main/resources/static/assets/img/error-404-monochrome.svg
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/datatables-simple-demo.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/401.html
  src/main/resources/templates/404.html
  src/main/resources/templates/500.html
  src/main/resources/templates/charts.html
  src/main/resources/templates/commonNav.html
  src/main/resources/templates/fragments/common_sidebar.html
  src/main/resources/templates/fragments/common_top_nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout-sidenav-light.html
  src/main/resources/templates/layout-static.html
  src/main/resources/templates/login.html
  src/main/resources/templates/password.html
  src/main/resources/templates/register.html
  src/main/resources/templates/tables.html
Labels: ✨ Feature

#12 [COMMON] 카테고리 기본 뼈대 추가
  .github/pull_request_template
  src/main/java/com/ani/taku_backend/admin/controller/AdminController.java
  src/main/java/com/ani/taku_backend/category/controller/CategoryController.java
  src/main/java/com/ani/taku_backend/category/domain/dto/AniCategoryListDTO.java
  src/main/java/com/ani/taku_backend/category/domain/entity/AnimationGenre.java
  src/main/java/com/ani/taku_backend/category/domain/entity/Category.java
  src/main/java/com/ani/taku_backend/category/domain/repository/CategoryRepository.java
  src/main/java/com/ani/taku_backend/category/domain/repository/impl/CustomCategoryRepository.java
  src/main/java/com/ani/taku_backend/category/domain/repository/impl/CustomCategoryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/category/service/CategoryService.java
  src/main/resources/static/assets/demo/chart-area-demo.js
  src/main/resources/static/assets/demo/chart-bar-demo.js
  src/main/resources/static/assets/demo/chart-pie-demo.js
  src/main/resources/static/assets/demo/datatables-demo.js
  src/main/resources/static/assets/img/error-404-monochrome.svg
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/datatables-simple-demo.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/401.html
  src/main/resources/templates/404.html
  src/main/resources/templates/500.html
  src/main/resources/templates/charts.html
  src/main/resources/templates/commonNav.html
  src/main/resources/templates/fragments/common_sidebar.html
  src/main/resources/templates/fragments/common_top_nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout-sidenav-light.html
  src/main/resources/templates/layout-static.html
  src/main/resources/templates/login.html
  src/main/resources/templates/password.html
  src/main/resources/templates/register.html
  src/main/resources/templates/tables.html
Labels: ✨ Feature

#13 [Auth] 인증 API 개발 , User CRD 개발
  build.gradle
  src/main/java/com/ani/taku_backend/auth/controller/AuthController.java
  src/main/java/com/ani/taku_backend/auth/handler/OAuth2AuthenticationHandler.java
  src/main/java/com/ani/taku_backend/auth/service/OAuth2LogoutService.java
  src/main/java/com/ani/taku_backend/auth/service/OAuth2UserService.java
  src/main/java/com/ani/taku_backend/auth/util/JwtUtil.java
  src/main/java/com/ani/taku_backend/common/enums/ProviderType.java
  src/main/java/com/ani/taku_backend/common/enums/UserRole.java
  src/main/java/com/ani/taku_backend/common/exception/FileException.java
  src/main/java/com/ani/taku_backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ani/taku_backend/common/exception/JwtException.java
  src/main/java/com/ani/taku_backend/common/exception/UserException.java
  src/main/java/com/ani/taku_backend/common/service/RedisService.java
  src/main/java/com/ani/taku_backend/config/RedisConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityPathConfig.java
  src/main/java/com/ani/taku_backend/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/ani/taku_backend/config/filter/RefreshTokenFilter.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/java/com/ani/taku_backend/user/model/dto/OAuthUserInfo.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
  src/main/java/com/ani/taku_backend/user/model/dto/RequestRegisterUser.java
  src/main/java/com/ani/taku_backend/user/model/entity/User.java
  src/main/java/com/ani/taku_backend/user/repository/UserRepository.java
  src/main/java/com/ani/taku_backend/user/service/UserService.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/login.html
Labels: ✨ Feature

#14 [Commom] Security Context User 조회 AOP 추가
  src/main/java/com/ani/taku_backend/common/annotation/RequireUser.java
  src/main/java/com/ani/taku_backend/common/aop/SecurityAspect.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
Labels: ✨ Feature

#7 Feat/common response : 공통반환객체 설계
  .gitignore
  src/main/java/com/ani/taku_backend/global/advice/ApiResponseStatusAdvice.java
  src/main/java/com/ani/taku_backend/global/exception/CustomException.java
  src/main/java/com/ani/taku_backend/global/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/global/exception/ExceptionController.java
  src/main/java/com/ani/taku_backend/global/exception/ExceptionDto.java
  src/main/java/com/ani/taku_backend/global/response/ApiResponse.java
Labels: ✨ Feature

#16 Feature/241219 status enum
  src/main/java/com/ani/taku_backend/common/enums/StatusType.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
  src/main/java/com/ani/taku_backend/user/service/UserService.java
Labels: 🔨 Refactor

#18 [Post] 커뮤니티 게시글 조회 API 개발 - 조건에 따른 정렬 기능과 검색어 조회 기능 포함
  src/main/java/com/ani/taku_backend/common/enums/SortFilterType.java
  src/main/java/com/ani/taku_backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListResponseDTO.java
  src/main/java/com/ani/taku_backend/post/model/entity/Post.java
  src/main/java/com/ani/taku_backend/post/repository/PostRepository.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustom.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/test/java/com/ani/taku_backend/post/repository/PostRepositoryTest.java
Labels: ✨ Feature

#20 [ADMIN] 금칙어 테이블 엔티티 , 도메인 추가
  src/main/java/com/ani/taku_backend/admin/domain/entity/ProfanityFilter.java
  src/main/java/com/ani/taku_backend/admin/domain/repository/ProfanityFilterRepository.java
  src/main/java/com/ani/taku_backend/admin/service/ProfanityFilterService.java
Labels: ✨ Feature

#32 [COMMON RESPONSE] Handler 통일로 CustomException핸들링 불가 현상 해소
  build.gradle
  src/main/java/com/ani/taku_backend/.DS_Store
  src/main/java/com/ani/taku_backend/common/ApiConstants.java
  src/main/java/com/ani/taku_backend/common/advice/ApiResponseStatusAdvice.java
  src/main/java/com/ani/taku_backend/common/exception/AlreadyExistsException.java
  src/main/java/com/ani/taku_backend/common/exception/DuckwhoException.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/common/exception/ExceptionDto.java
  src/main/java/com/ani/taku_backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ani/taku_backend/common/model/MainResponse.java
  src/main/java/com/ani/taku_backend/common/response/ApiResponse.java
  src/main/java/com/ani/taku_backend/example/controller/ExampleController.java
  src/main/java/com/ani/taku_backend/global/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/global/exception/ExceptionController.java
  src/main/java/com/ani/taku_backend/test/TestExceptionController.java
Labels: 🐞 BugFix

#19 [Category] Create API
  build.gradle
  src/main/java/com/ani/taku_backend/category/controller/RestCategoryController.java
  src/main/java/com/ani/taku_backend/category/domain/dto/RequestCategoryCreateDTO.java
  src/main/java/com/ani/taku_backend/category/domain/dto/ResponseCategoryDTO.java
  src/main/java/com/ani/taku_backend/category/domain/entity/Category.java
  src/main/java/com/ani/taku_backend/category/domain/entity/CategoryGenre.java
  src/main/java/com/ani/taku_backend/category/domain/entity/CategoryImage.java
  src/main/java/com/ani/taku_backend/category/domain/repository/CategoryRepository.java
  src/main/java/com/ani/taku_backend/category/service/CategoryService.java
  src/main/java/com/ani/taku_backend/common/model/dto/CreateImageDTO.java
  src/main/java/com/ani/taku_backend/common/model/entity/Image.java
  src/main/java/com/ani/taku_backend/common/service/ImageService.java
  src/main/java/com/ani/taku_backend/common/util/FileUtil.java
  src/main/java/com/ani/taku_backend/common/util/KoreanUtil.java
  src/main/java/com/ani/taku_backend/common/util/StringSimilarity.java
  src/main/java/com/ani/taku_backend/config/ModelMapperConfig.java
  src/main/java/com/ani/taku_backend/global/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
  src/main/java/com/ani/taku_backend/user/repository/BlackUserRepository.java
  src/main/java/com/ani/taku_backend/user/service/BlackUserService.java
  src/main/resources/sql/data.sql
Labels: ✨ Feature

#37 [Common] MongoDB 설정 추가
  build.gradle
  src/main/java/com/ani/taku_backend/TakuProjectApplication.java
  src/main/java/com/ani/taku_backend/config/MongoConfig.java
  src/main/java/com/ani/taku_backend/config/ObjectMapperConfig.java
Labels: ⚙ Setting

#41 [USER] HotFix UserAPI Response + Token Validate API
  src/main/java/com/ani/taku_backend/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/java/com/ani/taku_backend/user/repository/UserRepository.java
  src/main/java/com/ani/taku_backend/user/service/UserService.java
Labels: 🐞 BugFix

#42 [Profanity] DTO 이름 변경
  src/main/java/com/ani/taku_backend/admin/controller/ProfanityController.java
  src/main/java/com/ani/taku_backend/admin/domain/dto/ProfannityResponseDTO.java
  src/main/java/com/ani/taku_backend/admin/service/ProfanityFilterService.java
Labels: 🐞 BugFix

#40 [CATEGORY] ApiResponse사용하도록 수정
  src/main/java/com/ani/taku_backend/category/controller/RestCategoryController.java
  src/main/java/com/ani/taku_backend/category/service/CategoryService.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
Labels: 🐞 BugFix

#39 [FEATURE][BUGFIX] POST CRUD 기능 개발
  .gitignore
  src/main/java/com/ani/taku_backend/.DS_Store
  src/main/java/com/ani/taku_backend/annotation/ViewCountChecker.java
  src/main/java/com/ani/taku_backend/auth/controller/AuthController.java
  src/main/java/com/ani/taku_backend/category/controller/RestCategoryController.java
  src/main/java/com/ani/taku_backend/category/domain/repository/impl/CustomCategoryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/category/service/CategoryService.java
  src/main/java/com/ani/taku_backend/common/baseEntity/BaseTimeEntity.java
  src/main/java/com/ani/taku_backend/common/exception/PostException.java
  src/main/java/com/ani/taku_backend/common/model/dto/ImageCreateRequestDTO.java
  src/main/java/com/ani/taku_backend/common/model/entity/Image.java
  src/main/java/com/ani/taku_backend/common/repository/ImageRepository.java
  src/main/java/com/ani/taku_backend/config/WebConfig.java
  src/main/java/com/ani/taku_backend/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostCreateUpdateRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListResponseDTO.java
  src/main/java/com/ani/taku_backend/post/model/entity/CommunityImage.java
  src/main/java/com/ani/taku_backend/post/model/entity/Post.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustom.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/service/PostReadService.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/post/viewcount/helper/ProductCookieHelper.java
  src/main/java/com/ani/taku_backend/post/viewcount/helper/ProductCookieHelperImpl.java
  src/main/java/com/ani/taku_backend/post/viewcount/resolver/ViewCountCheckerResolver.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
  src/main/java/com/ani/taku_backend/user/model/entity/User.java
  src/test/java/com/ani/taku_backend/post/repository/PostRepositoryTest.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#45 [Test][BudFix][Refactor] Post CRUD 통합 테스트 완료 및 리펙토링 (Dev 브렌치 통합 과정에서 발생한 버그 픽스)
  build.gradle
  src/main/java/com/ani/taku_backend/admin/controller/ProfanityController.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/post/model/entity/CommunityImage.java
  src/main/java/com/ani/taku_backend/post/model/entity/Post.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/resources/sql/data.sql
  src/test/java/com/ani/taku_backend/post/service/PostServiceTest.java
  src/test/java/com/ani/taku_backend/post/service/TestFixture.java
Labels: ✅ Test, 🐞 BugFix, 🔨 Refactor

#47 [TEST][BUGFIX] updatePost에서 넘어온 이미지가 없을 때 삭제가 되지 않았던 버그를 수정
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/test/java/com/ani/taku_backend/post/service/PostServiceTest.java
Labels: ✅ Test, 🐞 BugFix

#51 [HOTFIX] User Entity 수정
  src/main/java/com/ani/taku_backend/auth/handler/OAuth2AuthenticationHandler.java
  src/main/java/com/ani/taku_backend/auth/util/JwtUtil.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/java/com/ani/taku_backend/user/model/dto/UserDTO.java
  src/main/java/com/ani/taku_backend/user/model/entity/User.java
Labels: 🐞 BugFix

#52 [Hotfix] response class 관련 네이밍 수정
  src/main/java/com/ani/taku_backend/admin/controller/ProfanityController.java
  src/main/java/com/ani/taku_backend/auth/controller/AuthController.java
  src/main/java/com/ani/taku_backend/category/controller/RestCategoryController.java
  src/main/java/com/ani/taku_backend/common/advice/CommonResponseStatusAdvice.java
  src/main/java/com/ani/taku_backend/common/annotation/ViewCountChecker.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ani/taku_backend/common/response/ApiResponse.java
  src/main/java/com/ani/taku_backend/common/response/CommonResponse.java
  src/main/java/com/ani/taku_backend/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/ani/taku_backend/example/controller/ExampleController.java
  src/main/java/com/ani/taku_backend/global/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/viewcount/resolver/ViewCountCheckerResolver.java
  src/main/java/com/ani/taku_backend/test/TestExceptionController.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
Labels: 🐞 BugFix

#55 [setting] CORS 전체 허용 ( 프론트엔드 테스트를 위함 )
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
Labels: ⚙ Setting
