Repository taku-project/taku-backend, pull requests merged in 2025-01, with the labels that each got.

#58 [feature] view check aop + annotaion
  src/main/java/com/ani/taku_backend/common/annotation/CheckViewCount.java
  src/main/java/com/ani/taku_backend/common/aop/ViewCountAspect.java
  src/main/java/com/ani/taku_backend/common/enums/ViewType.java
  src/main/java/com/ani/taku_backend/common/service/RedisService.java
Labels: ✨ Feature

#57 [feature] Shorts comment & reply comment CRUD
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ani/taku_backend/common/service/ExtractKeywordService.java
  src/main/java/com/ani/taku_backend/common/util/ObjectIdUtil.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityPathConfig.java
  src/main/java/com/ani/taku_backend/shorts/controller/ShortsController.java
  src/main/java/com/ani/taku_backend/shorts/domain/dto/ShortsCommentCreateReqDTO.java
  src/main/java/com/ani/taku_backend/shorts/domain/dto/ShortsCommentDTO.java
  src/main/java/com/ani/taku_backend/shorts/domain/dto/ShortsCommentUpdateReqDTO.java
  src/main/java/com/ani/taku_backend/shorts/domain/dto/ShortsInfoResDTO.java
  src/main/java/com/ani/taku_backend/shorts/domain/dto/res/PopularityMaticResDTO.java
  src/main/java/com/ani/taku_backend/shorts/service/ShortsService.java
  src/main/java/com/ani/taku_backend/shorts/service/ShortsServiceImpl.java
  src/main/java/com/ani/taku_backend/user/repository/UserRepository.java
  src/test/java/com/ani/taku_backend/Shorts/ShortsTest.java
Labels: ✨ Feature

#50 [FEAT] 시세 조회 도메인 구현
  src/main/java/com/ani/taku_backend/TakuProjectApplication.java
  src/main/java/com/ani/taku_backend/common/config/SchedulingConfig.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/common/model/entity/Image.java
  src/main/java/com/ani/taku_backend/common/repository/ImageRepository.java
  src/main/java/com/ani/taku_backend/common/service/FileService.java
  src/main/java/com/ani/taku_backend/common/service/ImageService.java
  src/main/java/com/ani/taku_backend/common/service/RedisService.java
  src/main/java/com/ani/taku_backend/common/util/RedisKeyUtil.java
  src/main/java/com/ani/taku_backend/config/MongoConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityPathConfig.java
  src/main/java/com/ani/taku_backend/jangter/controller/DuckuJangterController.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductCreateRequestDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductFindDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductUpdateRequestDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/ItemCategories.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/JangterImages.java
  src/main/java/com/ani/taku_backend/jangter/repository/DuckuJangterRepository.java
  src/main/java/com/ani/taku_backend/jangter/repository/ItemCategoriesRepository.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/main/java/com/ani/taku_backend/jangter/service/viewcount/ViewCountBatchService.java
  src/main/java/com/ani/taku_backend/jangter/service/viewcount/ViewCountService.java
  src/main/java/com/ani/taku_backend/marketprice/config/CacheConfig.java
  src/main/java/com/ani/taku_backend/marketprice/config/DateConfig.java
  src/main/java/com/ani/taku_backend/marketprice/controller/CompletedDealController.java
  src/main/java/com/ani/taku_backend/marketprice/controller/MarketPriceStatsController.java
  src/main/java/com/ani/taku_backend/marketprice/model/constant/GraphDisplayOption.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/MarketPriceSearchResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/PriceGraphRequestDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/PriceGraphResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/SimilarProductResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/WeeklyStatsResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/entity/CompletedDeal.java
  src/main/java/com/ani/taku_backend/marketprice/model/entity/MarketPriceStats.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealQueryRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealQueryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/MarketPriceStatsQueryRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/MarketPriceStatsQueryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/marketprice/repository/MarketPriceStatsRepository.java
  src/main/java/com/ani/taku_backend/marketprice/service/CompletedDealService.java
  src/main/java/com/ani/taku_backend/marketprice/service/MarketPriceStatsService.java
  src/main/java/com/ani/taku_backend/marketprice/util/DateTimeUtil.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfBatchScheduler.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfBatchService.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfCalculator.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfService.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/entity/Post.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/user/repository/BlackUserRepository.java
  src/main/resources/ValidationMessages.properties
  src/main/resources/sql/data.sql
  src/test/java/com/ani/taku_backend/common/service/ExtractKeywordServiceTest.java
  src/test/java/com/ani/taku_backend/marketprice/service/DealPriceServiceMockTest.java
  src/test/java/com/ani/taku_backend/post/service/PostServiceTest.java
  src/test/java/com/ani/taku_backend/post/service/TestFixture.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#60 [FEATURE] 덕후장터 CRUD 개발 (전체 목록 조회 제외)
  build.gradle
  src/main/java/com/ani/taku_backend/common/service/ImageService.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductFindDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/test/java/com/ani/taku_backend/post/service/PostServiceTest.java
  src/test/java/com/ani/taku_backend/post/service/TestFixture.java
Labels: ✨ Feature

#64 [Feature][Refactor][BugFix][Test] Posts/Comments/Jangter 기능 개발 및 리펙토링, 버그수정
  src/main/java/com/ani/taku_backend/category/service/CategoryService.java
  src/main/java/com/ani/taku_backend/comments/controller/CommentsController.java
  src/main/java/com/ani/taku_backend/comments/model/dto/CommentsCreateRequestDTO.java
  src/main/java/com/ani/taku_backend/comments/model/dto/CommentsUpdateRequestDTO.java
  src/main/java/com/ani/taku_backend/comments/model/entity/Comments.java
  src/main/java/com/ani/taku_backend/comments/repository/CommentsRepository.java
  src/main/java/com/ani/taku_backend/comments/service/CommentsService.java
  src/main/java/com/ani/taku_backend/common/enums/SortFilterType.java
  src/main/java/com/ani/taku_backend/common/exception/PostException.java
  src/main/java/com/ani/taku_backend/common/repository/ImageRepository.java
  src/main/java/com/ani/taku_backend/common/service/FileService.java
  src/main/java/com/ani/taku_backend/common/service/ImageService.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityPathConfig.java
  src/main/java/com/ani/taku_backend/jangter/controller/DuckuJangterController.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostCreateRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListResponseDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostUpdateRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/entity/CommunityImage.java
  src/main/java/com/ani/taku_backend/post/model/entity/Post.java
  src/main/java/com/ani/taku_backend/post/repository/PostRepository.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustom.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/repository/impl/dto/FindAllPostQuerydslDTO.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/shorts/service/ShortsServiceImpl.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/java/com/ani/taku_backend/user/model/dto/OAuthUserInfo.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
  src/main/java/com/ani/taku_backend/user/model/dto/RequestRegisterUser.java
  src/main/java/com/ani/taku_backend/user/model/dto/UserDTO.java
  src/main/java/com/ani/taku_backend/user/model/entity/User.java
  src/main/java/com/ani/taku_backend/user/service/BlackUserService.java
  src/main/resources/messages.properties
  src/test/java/com/ani/taku_backend/post/service/PostServiceTest.java
  src/test/java/com/ani/taku_backend/post/service/TestFixture.java
Labels: ✨ Feature, ✅ Test, 🐞 BugFix, 🔨 Refactor

#67 [HOTFIX] 로그인 요청시 header에 유저정보 추가
  src/main/java/com/ani/taku_backend/auth/handler/OAuth2AuthenticationHandler.java
  src/main/java/com/ani/taku_backend/auth/service/OAuth2UserService.java
Labels: ✨ Feature

#70 [feature] google OAuth2 연동 개발 [Refactor] 로그아웃 API 스웨거 작성 및 ErrorCode 수정
  src/main/java/com/ani/taku_backend/auth/controller/AuthController.java
  src/main/java/com/ani/taku_backend/auth/service/OAuth2LogoutService.java
  src/main/java/com/ani/taku_backend/auth/service/OAuth2UserService.java
  src/main/java/com/ani/taku_backend/auth/util/JwtUtil.java
  src/main/java/com/ani/taku_backend/common/enums/ProviderType.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/config/MongoConfig.java
  src/main/java/com/ani/taku_backend/user/controller/UserController.java
  src/main/resources/sql/data.sql
Labels: ✨ Feature, 🔨 Refactor

#75 [Feature] Post 좋아요 개발
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/post/controller/PostInteractionController.java
  src/main/java/com/ani/taku_backend/post/service/PostInteractionService.java
Labels: ✨ Feature, ⚙ Setting

#68 [MarketPrice] 시세 조회 도메인 구현 및 통합테스트
  .gitignore
  build.gradle
  qodana.yaml
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/common/exception/PostException.java
  src/main/java/com/ani/taku_backend/common/util/RedisKeyUtil.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityPathConfig.java
  src/main/java/com/ani/taku_backend/jangter/controller/DuckuJangterController.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductFindDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/repository/DuckuJangterRepository.java
  src/main/java/com/ani/taku_backend/jangter/service/viewcount/ViewCountBatchService.java
  src/main/java/com/ani/taku_backend/jangter/service/viewcount/ViewCountService.java
  src/main/java/com/ani/taku_backend/marketprice/config/CacheConfig.java
  src/main/java/com/ani/taku_backend/marketprice/config/DateConfig.java
  src/main/java/com/ani/taku_backend/marketprice/config/SchedulingConfig.java
  src/main/java/com/ani/taku_backend/marketprice/controller/CompletedDealController.java
  src/main/java/com/ani/taku_backend/marketprice/controller/MarketPriceStatsController.java
  src/main/java/com/ani/taku_backend/marketprice/model/constant/GraphDisplayOption.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/MarketPriceSearchResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/PriceGraphRequestDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/PriceGraphResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/SimilarProductResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/WeeklyStatsResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/entity/CompletedDeal.java
  src/main/java/com/ani/taku_backend/marketprice/model/entity/MarketPriceStats.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealQueryRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealQueryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/MarketPriceStatsQueryRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/MarketPriceStatsQueryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/marketprice/repository/MarketPriceStatsRepository.java
  src/main/java/com/ani/taku_backend/marketprice/service/CompletedDealService.java
  src/main/java/com/ani/taku_backend/marketprice/service/MarketPriceStatsService.java
  src/main/java/com/ani/taku_backend/marketprice/util/DateTimeUtil.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfBatchScheduler.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfBatchService.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfCalculator.java
  src/main/java/com/ani/taku_backend/marketprice/util/batch/TfidfService.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostCreateUpdateRequestDTO.java
  src/main/resources/ValidationMessages.properties
  src/main/resources/logback-spring.xml
  src/test/java/com/ani/taku_backend/ContainerNameTest.java
  src/test/java/com/ani/taku_backend/config/BaseTestConfiguration.java
  src/test/java/com/ani/taku_backend/config/DatabaseConnectionTest.java
  src/test/java/com/ani/taku_backend/config/TestRedisConfiguration.java
  src/test/java/com/ani/taku_backend/config/TestSecurityConfig.java
  src/test/java/com/ani/taku_backend/marketprice/config/TestRedisConfiguration.java
  src/test/java/com/ani/taku_backend/marketprice/service/CompletedDealServiceTest.java
Labels: ✅ Test, 🐞 BugFix

#80 [Refactor][BugFix] 커뮤니티 게시글 스웨거,DTO 리펙토링 및 게시글 업데이트 시 이미지 로직 버그 수정
  src/main/java/com/ani/taku_backend/common/service/ImageService.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/controller/PostInteractionController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostCreateRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostCreateUpdateRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostUpdateRequestDTO.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
Labels: 🐞 BugFix, 🔨 Refactor

#76 [hotfix] 쇼츠 댓글조회 api수정
  src/main/java/com/ani/taku_backend/shorts/domain/dto/ShortsCommentDTO.java
  src/main/java/com/ani/taku_backend/shorts/service/ShortsServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#73 [feature] 덕후장터 유저 interaction 추가
  src/main/java/com/ani/taku_backend/common/annotation/RequireUser.java
  src/main/java/com/ani/taku_backend/common/aop/SecurityAspect.java
  src/main/java/com/ani/taku_backend/common/enums/LogType.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/filter/PublicEndpointFilter.java
  src/main/java/com/ani/taku_backend/config/filter/RefreshTokenFilter.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/UserInteraction.java
  src/main/java/com/ani/taku_backend/jangter/service/UserInteractionService.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
Labels: ✨ Feature

#72 [feature] 공통 요청 api작업을 위한 코드 추가 및 수정
  src/main/java/com/ani/taku_backend/common/annotation/RequireUser.java
  src/main/java/com/ani/taku_backend/common/aop/SecurityAspect.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/filter/PublicEndpointFilter.java
  src/main/java/com/ani/taku_backend/config/filter/RefreshTokenFilter.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
Labels: ✨ Feature

#74 [feature] 장터 상품 추천api
  src/main/java/com/ani/taku_backend/common/model/entity/Bookmark.java
  src/main/java/com/ani/taku_backend/common/repository/BookmarkRepository.java
  src/main/java/com/ani/taku_backend/common/service/BookmarkService.java
  src/main/java/com/ani/taku_backend/jangter/controller/DuckuJangterController.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductRecommendResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangterBookmark.java
  src/main/java/com/ani/taku_backend/jangter/repository/DuckuJangterRepository.java
  src/main/java/com/ani/taku_backend/jangter/repository/impl/DuckuJangterRepositoryCustom.java
  src/main/java/com/ani/taku_backend/jangter/repository/impl/DuckuJangterRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/jangter/score/ScoreCalculator.java
  src/main/java/com/ani/taku_backend/jangter/score/calculator/BookmarkScoreCalculator.java
  src/main/java/com/ani/taku_backend/jangter/score/calculator/PurchaseHistoryScoreCalculator.java
  src/main/java/com/ani/taku_backend/jangter/score/calculator/SearchHistoryScoreCalculator.java
  src/main/java/com/ani/taku_backend/jangter/score/calculator/ViewHistoryScoreCalculator.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/main/java/com/ani/taku_backend/jangter/vo/UserBookmarkHistory.java
  src/main/java/com/ani/taku_backend/jangter/vo/UserPurchaseHistory.java
  src/main/java/com/ani/taku_backend/jangter/vo/UserSearchHistory.java
Labels: ✨ Feature

#79 [ 시세 그래프 응답 DTO] datapoints에 상품 id와 title까지 함께 전달
  src/main/java/com/ani/taku_backend/marketprice/controller/CompletedDealController.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/MarketPriceSearchResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/PriceGraphRequestDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/PriceGraphResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/SimilarProductResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/WeeklyStatsResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/entity/MarketPriceStats.java
Labels: 🔨 Refactor

#78 [Chat] WebSocket 기반 채팅 기능 구현
  build.gradle
  src/main/java/com/ani/taku_backend/chatroom/controller/ChatRoomController.java
  src/main/java/com/ani/taku_backend/chatroom/model/constant/ChatRoomStatus.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/ChatRoomRequestDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/ChatRoomResponseDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/entity/ChatRoom.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatRoomService.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/config/MessageBrokerConfig.java
  src/main/java/com/ani/taku_backend/config/WebConfig.java
Labels: ✨ Feature

#89 [SHORTS] 상호작용 Bug fix
  src/main/java/com/ani/taku_backend/admin/category/repository/CustomAdminCategoryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/shorts/domain/entity/Interaction.java
  src/main/java/com/ani/taku_backend/shorts_interaction/repository/CustomInteractionRepository.java
  src/main/java/com/ani/taku_backend/shorts_interaction/repository/CustomInteractionRepositoryImpl.java
  src/main/java/com/ani/taku_backend/shorts_interaction/service/InteractionServiceImpl.java
Labels: 🐞 BugFix

#91 [FEATURE] 버그 수정
  src/main/java/com/ani/taku_backend/shorts/domain/entity/Shorts.java
  src/main/java/com/ani/taku_backend/shorts/service/ShortsServiceImpl.java
Labels: 🐞 BugFix

#90 [Feature] 프론트엔드 요구사항 반영 [Refactor] Service계층 추상화 및 삭제 시 카테고리ID 요청 삭제
  src/main/java/com/ani/taku_backend/comments/service/CommentsService.java
  src/main/java/com/ani/taku_backend/comments/service/CommentsServiceImpl.java
  src/main/java/com/ani/taku_backend/common/exception/PostException.java
  src/main/java/com/ani/taku_backend/config/SecurityPathConfig.java
  src/main/java/com/ani/taku_backend/jangter/controller/DuckuJangterController.java
  src/main/java/com/ani/taku_backend/jangter/controller/ItemCategoriesController.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ItemCategoriesResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductFindDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/JangterImages.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterServiceImpl.java
  src/main/java/com/ani/taku_backend/jangter/service/ItemCategoriesService.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/post/service/PostServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#93 [Chat] 채팅방 안 읽은 메시지 수 조회 기능 구현
  src/main/java/com/ani/taku_backend/chatroom/controller/ChatRoomController.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/ChatroomMetaInfo.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/ParticipantInfo.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/Participants.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/ChatRoomRequestDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/ChatRoomResponseDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/entity/ChatRoom.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ChatroomMetaRepository.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatRoomService.java
Labels: ✨ Feature

#92 [hotfix] r2 image bucket에 맞게 저장 하도록 수정
  src/main/java/com/ani/taku_backend/category/controller/ApiCategoryController.java
  src/main/java/com/ani/taku_backend/category/service/CategoryServiceImpl.java
Labels: 🐞 BugFix

#97 [Feature] 장터 랭킹 조회 api
  src/main/java/com/ani/taku_backend/common/enums/PeriodType.java
  src/main/java/com/ani/taku_backend/common/enums/RankType.java
  src/main/java/com/ani/taku_backend/jangter/controller/DuckuJangterController.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/CategoryGroupCountDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductRankInfoResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductScoreDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductViewAndBookmarkDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/rank/JangterRankBase.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/rank/JangterRankStats.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/rank/JangterRankType.java
  src/main/java/com/ani/taku_backend/jangter/repository/DuckuJangterRepository.java
  src/main/java/com/ani/taku_backend/jangter/repository/JangterRankBaseRepository.java
  src/main/java/com/ani/taku_backend/jangter/repository/JangterRankTypeRepository.java
  src/main/java/com/ani/taku_backend/jangter/repository/impl/DuckuJangterRepositoryCustom.java
  src/main/java/com/ani/taku_backend/jangter/repository/impl/DuckuJangterRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterServiceImpl.java
  src/main/java/com/ani/taku_backend/jangter/util/batch/JangterRankBatchService.java
  src/main/java/com/ani/taku_backend/jangter/util/batch/JangterRankScheduler.java
Labels: ✨ Feature

#94 [Feature] FileController에 이미지/비디오 업로드 다운로드 부분 구분
  src/main/java/com/ani/taku_backend/common/controller/FileController.java
Labels: ✨ Feature
