Repository taku-project/taku-backend, pull requests merged in 2025-03, with the labels that each got.

#128 [hotfix][Chat] 무한 스크롤 지원 채팅 이력 조회 API 구현
  src/main/java/com/ani/taku_backend/chatroom/StompHandler.java
  src/main/java/com/ani/taku_backend/chatroom/controller/ChatMessageController.java
  src/main/java/com/ani/taku_backend/chatroom/controller/ChatRoomController.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/ParticipantInfo.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/Participants.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/ChatReadStatusDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/request/ChatMessageRequestDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/request/ChatRoomRequestDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/response/ChatMessageListResponseDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/response/ChatMessageResponseDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/response/ChatRoomResponseDTO.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ChatMessageRepository.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatAuthorizationService.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatRoomService.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatService.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/test/java/com/ani/taku_backend/ContainerNameTest.java
  src/test/java/com/ani/taku_backend/chatroom/ChatRoomWebSocketTest.java
Labels: ✨ Feature

#129 [BugFix] kakao 로그인 시 발생하는 버그 해결
  src/main/java/com/ani/taku_backend/auth/service/OAuth2UserService.java
  src/main/java/com/ani/taku_backend/user/repository/UserRepository.java
  src/test/java/com/ani/taku_backend/init/CommentsInit.java
  src/test/java/com/ani/taku_backend/init/ItemCategoriesInit.java
  src/test/java/com/ani/taku_backend/init/JangterInit.java
  src/test/java/com/ani/taku_backend/init/PostInit.java
  src/test/java/com/ani/taku_backend/post/service/PostInteractionServiceTest.java
Labels: 🐞 BugFix

#135 [CHAT] DTO에서 비즈니스 로직 분리 및 도메인 책임 강화
  src/main/java/com/ani/taku_backend/chatroom/domain/document/ChatRoomMetaInfo.java
  src/main/java/com/ani/taku_backend/chatroom/domain/document/Participants.java
  src/main/java/com/ani/taku_backend/chatroom/domain/entity/ChatRoom.java
  src/main/java/com/ani/taku_backend/chatroom/domain/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/ani/taku_backend/chatroom/domain/repository/ChatRoomRepositoryImpl.java
  src/main/java/com/ani/taku_backend/chatroom/domain/vo/ChatRoomMessages.java
  src/main/java/com/ani/taku_backend/chatroom/dto/response/ChatRoomCompositeDTO.java
  src/main/java/com/ani/taku_backend/chatroom/dto/response/ChatRoomResponseDTO.java
  src/main/java/com/ani/taku_backend/chatroom/mapper/ChatRoomDtoConverter.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatRoomService.java
  src/main/java/com/ani/taku_backend/chatroom/service/command/ChatRoomCommandService.java
  src/main/java/com/ani/taku_backend/chatroom/service/query/ChatRoomQueryService.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/config/ModelMapperConfig.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
Labels: 🔨 Refactor
