Repository taku-project/taku-backend, pull requests merged in 2025-02, with the labels that each got.

#103 [Feature][Refactor] 커뮤니티 게시글 전체조회 관련 리펙토링 및 클라이언트 요청 반영
  src/main/java/com/ani/taku_backend/common/enums/InteractionType.java
  src/main/java/com/ani/taku_backend/common/enums/SortFilterType.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/controller/PostInteractionController.java
  src/main/java/com/ani/taku_backend/post/model/dto/FindPostQueryDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListRequestDTO.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostListResponseDTO.java
  src/main/java/com/ani/taku_backend/post/model/entity/PostInteraction.java
  src/main/java/com/ani/taku_backend/post/model/entity/PostInteractionCounter.java
  src/main/java/com/ani/taku_backend/post/model/enums/PostInteractionFields.java
  src/main/java/com/ani/taku_backend/post/repository/PostInteractionCounterRepository.java
  src/main/java/com/ani/taku_backend/post/repository/PostRepository.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostInteractionCounterRepositoryCustom.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostInteractionCounterRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustom.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/service/PostInteractionService.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/post/service/PostServiceImpl.java
  src/test/java/com/ani/taku_backend/init/CommentsInit.java
  src/test/java/com/ani/taku_backend/init/ItemCategoriesInit.java
  src/test/java/com/ani/taku_backend/init/JangterInit.java
  src/test/java/com/ani/taku_backend/init/PostInit.java
  src/test/java/com/ani/taku_backend/post/service/PostInteractionServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#104 [ BugFix] 수정한 커뮤니티 전체조회 api가 여러이미지를 반환하면 이미지의 개수만큼 게시글을 생성하는 문제 해결
  src/main/java/com/ani/taku_backend/post/repository/impl/PostRepositoryCustomImpl.java
Labels: 🐞 BugFix

#101 [Feature] 게시글 상세 조회 시 댓글 목록 포함 및 /조회수 관련 오류 수정
  src/main/java/com/ani/taku_backend/comments/model/dto/CommentsResponseDTO.java
  src/main/java/com/ani/taku_backend/comments/model/entity/Comments.java
  src/main/java/com/ani/taku_backend/comments/repository/CommentsRepository.java
  src/main/java/com/ani/taku_backend/comments/service/CommentsService.java
  src/main/java/com/ani/taku_backend/comments/service/CommentsServiceImpl.java
  src/main/java/com/ani/taku_backend/config/WebConfig.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/post/service/PostReadService.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/post/service/PostServiceImpl.java
  src/main/java/com/ani/taku_backend/post/viewcount/helper/ProductCookieHelperImpl.java
  src/main/java/com/ani/taku_backend/user/model/dto/PrincipalUser.java
Labels: ✨ Feature, 🐞 BugFix

#106 hotfix CORS PATCH 추가가
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
Labels: 🐞 BugFix

#109 [Feature] 로그인, 회원가입시 리다이렉트 url을 localhost와 서버에서 요청할때 각각 다르게 전송, 정보를 쿼리스트링으로 변경 및 추가 정보 전송
  src/main/java/com/ani/taku_backend/auth/handler/OAuth2AuthenticationHandler.java
  src/main/java/com/ani/taku_backend/auth/service/OAuth2UserService.java
  src/main/java/com/ani/taku_backend/config/MessageBrokerConfig.java
  src/main/java/com/ani/taku_backend/config/WebConfig.java
  src/main/resources/static/favicon.ico
Labels: ✨ Feature, 🔨 Refactor

#111 [Feature] 게시글 상세 조회 기능 개선 및 좋아요 확인 기능 구현 및 댓글 시스템 버그 수정
  src/main/java/com/ani/taku_backend/comments/model/dto/CommentsResponseDTO.java
  src/main/java/com/ani/taku_backend/comments/model/entity/Comments.java
  src/main/java/com/ani/taku_backend/comments/repository/CommentsRepository.java
  src/main/java/com/ani/taku_backend/comments/service/CommentsServiceImpl.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/post/model/entity/Post.java
  src/main/java/com/ani/taku_backend/post/model/entity/PostInteractionCounter.java
  src/main/java/com/ani/taku_backend/post/repository/PostRepository.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostInteractionCounterRepositoryCustom.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostInteractionCounterRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/service/PostServiceImpl.java
Labels: ✨ Feature, 🐞 BugFix

#112 [Feature] 상품 판매 상태 관리 시스템 구현
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/jangter/controller/DuckuJangterController.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductFindDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/ProductStatusDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/requestDto/FindRecommendFilteredProductsRequestDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/dto/requestDto/ProductStatusUpdateRequestDTO.java
  src/main/java/com/ani/taku_backend/jangter/model/entity/DuckuJangter.java
  src/main/java/com/ani/taku_backend/jangter/model/enums/ProductStatus.java
  src/main/java/com/ani/taku_backend/jangter/repository/DuckuJangterRepository.java
  src/main/java/com/ani/taku_backend/jangter/repository/DuckuJangterRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterService.java
  src/main/java/com/ani/taku_backend/jangter/service/DuckuJangterServiceImpl.java
  src/main/java/com/ani/taku_backend/marketprice/model/entity/MarketPriceStats.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/MarketPriceStatsRepository.java
  src/test/java/com/ani/taku_backend/jangter/service/DuckuJangterServiceTest.java
  src/test/java/com/ani/taku_backend/marketprice/service/CompletedDealServiceTest.java
Labels: ✨ Feature

#114 [HOTFIX][MarketPrice] 시세 조회 응답에 평균 판매 가격 추가
  src/main/java/com/ani/taku_backend/marketprice/model/dto/MarketPriceSearchResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/model/dto/WeeklyStatsResponseDTO.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealQueryRepository.java
  src/main/java/com/ani/taku_backend/marketprice/repository/CompletedDealQueryRepositoryImpl.java
  src/main/java/com/ani/taku_backend/marketprice/service/CompletedDealService.java
Labels: ✨ Feature

#116 [HOTFIX][Refactor] 게시글 상세 조회시 좋아요 여부 관련 버그 픽스 및 댓글 갯수 추가 구현
  src/main/java/com/ani/taku_backend/comments/repository/CommentsRepository.java
  src/main/java/com/ani/taku_backend/comments/service/CommentsService.java
  src/main/java/com/ani/taku_backend/comments/service/CommentsServiceImpl.java
  src/main/java/com/ani/taku_backend/common/annotation/ViewCountChecker.java
  src/main/java/com/ani/taku_backend/config/WebConfig.java
  src/main/java/com/ani/taku_backend/post/controller/PostController.java
  src/main/java/com/ani/taku_backend/post/model/dto/PostDetailResponseDTO.java
  src/main/java/com/ani/taku_backend/post/repository/impl/PostInteractionCounterRepositoryCustomImpl.java
  src/main/java/com/ani/taku_backend/post/service/PostService.java
  src/main/java/com/ani/taku_backend/post/service/PostServiceImpl.java
  src/main/java/com/ani/taku_backend/post/viewcount/helper/ProductCookieHelper.java
  src/main/java/com/ani/taku_backend/post/viewcount/helper/ProductCookieHelperImpl.java
  src/main/java/com/ani/taku_backend/post/viewcount/resolver/ViewCountCheckerResolver.java
Labels: ✨ Feature, 🐞 BugFix

#120 [Chat] 채팅 시스템 버그 픽스 및 문서화
  pom.xml
  src/main/java/com/ani/taku_backend/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/com/ani/taku_backend/bookmark/service/BookmarkService.java
  src/main/java/com/ani/taku_backend/chatroom/controller/ChatRoomController.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/ChatMessage.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/ChatRoomMetaInfo.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/ParticipantInfo.java
  src/main/java/com/ani/taku_backend/chatroom/model/document/Participants.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/ChatRoomRequestDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/dto/ChatRoomResponseDTO.java
  src/main/java/com/ani/taku_backend/chatroom/model/entity/ChatRoom.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ChatMessageRepository.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ChatRoomMetaInfoRepository.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ChatRoomMetaRepository.java
  src/main/java/com/ani/taku_backend/chatroom/repository/ParticipantInfoRepository.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatRoomService.java
  src/main/java/com/ani/taku_backend/chatroom/service/ChatService.java
  src/main/java/com/ani/taku_backend/common/exception/ErrorCode.java
  src/main/java/com/ani/taku_backend/config/SecurityConfig.java
  src/main/java/com/ani/taku_backend/config/SecurityPathConfig.java
Labels: 🐞 BugFix, 🔨 Refactor
